# Generated by Django 4.2.26 on 2025-11-28 10:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_account_id', models.TextField()),
                ('display_name', models.TextField(blank=True, null=True)),
                ('status', models.TextField(default='active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='BrokerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('display_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(unique=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='portfolio.user')),
            ],
        ),
        migrations.CreateModel(
            name='BrokerAccountCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credentials', models.JSONField()),
                ('encrypted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('broker_account', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='portfolio.brokeraccount')),
            ],
        ),
        migrations.AddField(
            model_name='brokeraccount',
            name='broker_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='broker_accounts', to='portfolio.brokertype'),
        ),
        migrations.AddField(
            model_name='brokeraccount',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_accounts', to='portfolio.portfolio'),
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.TextField()),
                ('symbol', models.TextField()),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=30)),
                ('price', models.DecimalField(decimal_places=6, max_digits=30)),
                ('currency', models.TextField(default='INR')),
                ('trade_type', models.TextField()),
                ('trade_time', models.DateTimeField()),
                ('meta', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('broker_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='portfolio.brokeraccount')),
            ],
            options={
                'indexes': [models.Index(fields=['broker_account'], name='portfolio_t_broker__23fb49_idx'), models.Index(fields=['symbol'], name='portfolio_t_symbol_735258_idx'), models.Index(fields=['trade_time'], name='portfolio_t_trade_t_4975c3_idx')],
            },
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_type', models.TextField()),
                ('symbol', models.TextField()),
                ('isin', models.TextField(blank=True, null=True)),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=30)),
                ('avg_price', models.DecimalField(decimal_places=6, max_digits=30)),
                ('currency', models.TextField(default='INR')),
                ('cost_value', models.DecimalField(blank=True, decimal_places=6, max_digits=30, null=True)),
                ('market_value', models.DecimalField(blank=True, decimal_places=6, max_digits=30, null=True)),
                ('as_of', models.DateTimeField()),
                ('source_snapshot_id', models.TextField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('broker_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='portfolio.brokeraccount')),
            ],
            options={
                'indexes': [models.Index(fields=['broker_account'], name='portfolio_h_broker__2118af_idx'), models.Index(fields=['symbol'], name='portfolio_h_symbol_b80c0d_idx'), models.Index(fields=['as_of'], name='portfolio_h_as_of_9ceee6_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='brokeraccount',
            constraint=models.UniqueConstraint(fields=('broker_type', 'external_account_id'), name='uniq_broker_account_per_broker_type'),
        ),
    ]
