# Generated by Django 4.2.10 on 2025-12-01 06:58

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BrokerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_account_id', models.TextField()),
                ('display_name', models.TextField(blank=True, null=True)),
                ('status', models.TextField(default='active')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='BrokerAccountCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('credentials', models.JSONField()),
                ('encrypted', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='BrokerType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.TextField(unique=True)),
                ('display_name', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Holding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=30)),
                ('avg_price', models.DecimalField(decimal_places=6, max_digits=30)),
                ('currency', models.TextField(default='INR')),
                ('as_of', models.DateTimeField()),
                ('source_snapshot_id', models.TextField(blank=True, null=True)),
                ('meta', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('description', models.TextField(blank=True, null=True)),
                ('is_default', models.BooleanField(default=False)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20)),
                ('isin', models.CharField(blank=True, max_length=20, null=True)),
                ('asset_type', models.CharField(max_length=30)),
                ('as_of', models.DateTimeField()),
                ('last_price', models.DecimalField(decimal_places=4, max_digits=12)),
                ('close_price', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
                ('received_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'stock_prices',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.TextField(unique=True)),
                ('name', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=6, max_digits=30)),
                ('price', models.DecimalField(decimal_places=6, max_digits=30)),
                ('currency', models.TextField(default='INR')),
                ('trade_type', models.TextField()),
                ('trade_time', models.DateTimeField()),
                ('meta', models.JSONField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('broker_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='portfolio.brokeraccount')),
                ('stock', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='transactions', to='portfolio.stock')),
            ],
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['symbol'], name='stock_price_symbol_3619dd_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['isin'], name='stock_price_isin_374b48_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['asset_type'], name='stock_price_asset_t_6bb300_idx'),
        ),
        migrations.AddIndex(
            model_name='stock',
            index=models.Index(fields=['as_of'], name='stock_price_as_of_7bab1c_idx'),
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('symbol', 'isin', 'asset_type', 'as_of'), name='uniq_stock_price_snapshot'),
        ),
        migrations.AddField(
            model_name='portfolio',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolios', to='portfolio.user'),
        ),
        migrations.AddField(
            model_name='holding',
            name='broker_account',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='holdings', to='portfolio.brokeraccount'),
        ),
        migrations.AddField(
            model_name='holding',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='holdings', to='portfolio.stock'),
        ),
        migrations.AddField(
            model_name='brokeraccountcredential',
            name='broker_account',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credential', to='portfolio.brokeraccount'),
        ),
        migrations.AddField(
            model_name='brokeraccount',
            name='broker_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='broker_accounts', to='portfolio.brokertype'),
        ),
        migrations.AddField(
            model_name='brokeraccount',
            name='portfolio',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='broker_accounts', to='portfolio.portfolio'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['broker_account'], name='portfolio_t_broker__23fb49_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['stock'], name='portfolio_t_stock_i_13bda0_idx'),
        ),
        migrations.AddIndex(
            model_name='transaction',
            index=models.Index(fields=['trade_time'], name='portfolio_t_trade_t_4975c3_idx'),
        ),
        migrations.AddIndex(
            model_name='holding',
            index=models.Index(fields=['broker_account'], name='portfolio_h_broker__2118af_idx'),
        ),
        migrations.AddIndex(
            model_name='holding',
            index=models.Index(fields=['stock'], name='portfolio_h_stock_i_efd323_idx'),
        ),
        migrations.AddIndex(
            model_name='holding',
            index=models.Index(fields=['as_of'], name='portfolio_h_as_of_9ceee6_idx'),
        ),
        migrations.AddConstraint(
            model_name='brokeraccount',
            constraint=models.UniqueConstraint(fields=('broker_type', 'external_account_id'), name='uniq_broker_account_per_broker_type'),
        ),
    ]
