# Generated by Django 4.2.10 on 2025-12-01 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='stock',
            name='uniq_stock_price_snapshot',
        ),
        migrations.AddConstraint(
            model_name='stock',
            constraint=models.UniqueConstraint(fields=('symbol', 'isin', 'asset_type'), name='uniq_stock_instrument'),
        ),
    ]
